# These are part of shell environment, append it to `zshrc` or `bashrc`, depends on what shell is used.
export GOROOT=/usr/local/go/
export GOPATH=~/Codes/gopath/
export GO111MODULE=on

export PATH="$PATH:/usr/local/bin/"

# Set prompt
PROMPT="[%n@%m %1~]# "

